apiVersion: v1
kind: Pod
metadata:
  name: pi-pod

spec:
  containers:
    - name: shell
      imagePullPolicy: IfNotPresent
      image: busybox
      tty: true
      stdin: true
  nodeSelector:
    device: pi