apiVersion: v1
kind: Pod
metadata:
  name: pod-share

spec:
  shareProcessNamespace: true
  containers:
    - name: shell
      imagePullPolicy: IfNotPresent
      image: busybox
      tty: true
      stdin: true
