kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ro
  namespace: dev
subjects:
- kind: ServiceAccount
  name: default
  namespace: dev
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
